import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutProvider from "./layoutProvider";
import { Web3Provider } from "./context/Web3Context";
import { bg, fg } from "@/colors";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark bg-[${bg}] text-[${fg}]`}
      >
        
        <Web3Provider>
        <LayoutProvider>
          {children}
        </LayoutProvider>
        </Web3Provider>
        
      </body>
    </html>
  );
}
